        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 17 19:02:20 2021
        MODULE COUNT0__genmod
          INTERFACE 
            SUBROUTINE COUNT0
            END SUBROUTINE COUNT0
          END INTERFACE 
        END MODULE COUNT0__genmod
